FROM ppc64le/ubuntu:18.04


ENV VERSION="v66"
ENV SO="Ubuntu18"
RUN apt-get update && apt-get install -y wget unzip
RUN wget http://sourceforge.net/projects/nmon/files/njmon_linux_binaries_$VERSION.zip
RUN unzip njmon_linux_binaries_$VERSION.zip -d /njmon

FROM ppc64le/ubuntu:18.04
COPY --from=0 /njmon/njmon_$SO_ppc64le_$VERSION /usr/bin/njmon

ADD entrypoint.sh /
WORKDIR /njmon-data

ENTRYPOINT ["/entrypoint.sh"]
